export const blogs = [
  {
    id: 'A1',
    pos: 1,
    title: 'PLAN YOUR PLOT TO IMPROVE YOUR STORY',
    date: 'SEPTEMBER 19, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2022/05/SpiderManNoWayHome002.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'What sounds better? Going out with no real place in mind to go to? or going out knowing exactly where you have to go? I mean, in both cases it’s not guaranteed that you’re gonna get to the destination. Maybe you meet some obstacle that doesn’t let you pass along the way. Things happen, okay? Thing is, if you were going nowhere, it really doesn’t matter if you overcome the obstacle, you just can go back or whatever. It is only when you have a destination that you’re compelled to move forward. Such metaphysical insight must be making our pantheon of philosophers wet their pants right now. Worry not, in this video we’re gonna expose the juicy elements of considering your plot before diving into a story. We’re not trying to convince you; we’re just telling you that… PLOT CAN MAKE YOUR STORY BETTER.',
    par2: 'You might be wondering, How? Just remember the previous analogy about going out, your plot is your roadmap for the external conflict of the story. Yes, there’s more than one type of conflict. When figuring out the plot, what you’re doing is figuring out the spine of your story, it’s the foundation on top of which everything else rests. A classic definition of it would be; “The main events of a story devised and presented as an interrelated sequence”. Now, these events refer to the external conflict as we said before, but also consider that, for the most part, they’re what the audience is gonna be watching and also it is definitely the selling point of any story. Like in Independence day, right? the plot of that movie was about an alien invasion. So, it covers the discovery of the invasion, the invasion itself and the final battle to free planet Earth. That’s a PLOT!',
    par3: 'There are two things in this definition that are worth thinking about: Main events: A sum of actions or events that occur in the story. Interrelated: A connected order for these actions or events to happen. So, what’s the difference between PLOT and STORY? Story is what happens. Plot is what happens in the connected order. An example of this: Story: A dude died and then a woman died. Plot: A dude died and then a woman died of grief. Got it? Okay, so “died of grief” implies a causal relation between both deaths, a connection.',
    quote: 'Let’s go back to that classic definition for a moment; “The main events of a story devised and presented as an interrelated sequence”.'
  },
  {
    id: 'B2',
    pos: 2,
    title: 'GUSTAV FREYTAG’S PYRAMID SCHEME',
    date: 'SEPTEMBER 26, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2022/04/Octopussy-010.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'Simplicity, that’s the word you’re looking for right now. Gustav Freytag’s pyramid must be the most elementary, yet deceitfully helpful map to think about a story. It’s composed of seven distinctive plot points that are often called the seven key steps to any story. So, which are the they? Exposition, Inciting incident, Rising action, Climax, Falling action, Resolution, Denouement. Now, let’s go one by one to try and figure out what do they mean, but also how to approach them in the best possible way! U in? Let’s go!',
    par2: 'Exposition; I know, the word itself sounds boring. Many people think or rather feel that exposition is the cancer of stories, well maybe in dialogue! Truth is, without due exposition there can’t be any story. So, what is this thing anyway? It’s the initial important background information that the reader/viewer must know in order to understand what’s coming next. It’s composed by: Setting, or the world in which the story happens. It’s the physical grounds of the whole thing, but also the culture and society. Previous events, facts or actions that happened before the beginning of the story, but that they’re relevant for us to know moving forward. Backstory, this is also referred to as the background of characters. Now, don’t go too far in building this backstory, limit yourself to write only those aspects of a character that can help your story move forward (only those things that are relevant for the story!). Inciting incident; This is the first major event in the story, the first true plot twist! An event that kicks off the action. The idea is for it to give us information about the main conflict that’s gonna happen later on and also may function as the protagonist introduction (not an obligation!). Rising action; This concept is not necessarily a single plot point, rather a series of events building towards the climax of the story. In classic storytelling, it’s composed of many obstacles that the antagonist puts in the protagonist way to prevent him from achieving a goal at the climax, but also from the continued efforts from the protagonist to keep moving towards this goal or objective. Climax; We’ve often heard about this idea of a climax, the point of maximum tension on a story. It’s the single most important event on the entire structure and, since the beginning of the story, all the action should lead, one way or another, up to this point. So, the idea is to set it up by building your rising action up to this point. Yet there’s another part about the climax that is worth keeping in mind. When thinking about character, the climax should be the moment of a mayor revelation. A point in which, with his/her back against the wall, the protagonist show’s us who he/she really is. Falling action; This is often called the fallout that comes after the climax. It’s a moment in which tension is cleared and revelations or reflections about the conflict happen. In modern storytelling, this is the part where the protagonist learns the true meaning of his/her quest and gets to understand the cost of their actions. Resolution; Simply put, this is the part of the story where the protagonist solves the main conflict or problem that was posed in the inciting incident, the objective is cleared!',
    par3: 'Simple enough, isn’t it? So now u can actually visualize your story by simply imagining these seven key steps to structure your story in a way that gives order and sense of motion to the plot! Really cool, uh? So, next we’ll be diving the relationship between plot and character, are u up for it? Best of lucks and remember… GO WRITE!',
    quote: 'Denouement; The ending of the story, where any remaining mystery or questions surrounding the plot are answered. In filmmaking there’s a long tradition of using the denouement to present what it’s called a metaphoric scene, one that poetically gives us a sense of the deeper meaning of the story.'
  },
  {
    id: 'C3',
    pos: 3,
    title: 'HOW CHARACTERS IMPROVE YOUR PLOT',
    date: 'OCTOBER 03, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2022/05/Apollo101_2036.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'There’s an old sayin’ in storytelling; Character + Action = Plot. Well, looks more like a mathematical proposition, but the important thing is that it tells a critical point about writing stories, characters drive the action and the result of their movement is the actual plot. John Gardner, the famous American writer, often said that there are actually only two kinds of plot. Someone goes on a journey; a stranger comes to town. Was he out of imagination when coining this idea? Not sure, but! He’s not far from the truth. What he’s actually saying is that stories involve the movement of certain character. Someone goes on a journey implies a movement to the exterior, into the unknown, a character going away. A stranger comes to town involves the unknown coming into the familiar by the hand of a new character entering a familiar world.',
    par2: 'Now, maybe Gardner only knew about the hero’s journey, I don’t know. Nowadays I feel we can find a different approach to storytelling in structures such as the virgin’s promise, which is more an inner journey (something we’ll definitely talk about later!). But the important thing to take from his words are the connection between a drive character (the one who acts) and the plot, which comes from this movement.',
    par3: 'Now, what is this will thing he keeps talking about? Simply put is the combination of a character’s desire and the drive to achieve this desire. A character wants something and goes into action to achieve this goal, the resulting path or journey drawn in the sands of time is what we often call plot. You liked that last reflection? Pretty neat, uh? Let’s join next time to talk about ways of thinking about characters, since they seem so important to storytelling! And remember… GO WRITE!!',
    quote: 'Another genius of storytelling, Hayao Miyasaki, has two phrases that can shade some light on this matter: What drives action is the WILL of the characters. You don’t depict fate, you depict WILL.'
  },
  {
    id: 'D4',
    pos: 4,
    title: 'QUESTIONS FOR CHARACTER DEVELOPMENT',
    date: 'OCTOBER 10, 2022',
    img: 'https://film-grab.com/wp-content/uploads/2022/02/The-Damned-013.jpg',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'I know, every time hearing something like “simple” or “fast” a natural inclination to distrust leads us to think there must be some catch, right? Well, you’re not far from the truth there, there are no easy ways into doing complex things, this much we all know. However! 5 simple questions can actually help you start your journey into the character, same way as a premise can start a journey into a plot! So, let’s dive into these questions one at a time in order to build our characters! First one is… What do they want?  Okay, so this question can be summarized in two aspects of a character’s motivation, this is because what they want is what brings them into action, and is composed of two distinctive traits. Desire, is a concrete goal the character wants to achieve. Need, is a change of personality, of the inner core of the character that needs to be accepted, fixed or changed entirely. What are their weaknesses? A weakness makes a character more interesting; it gives us an inside about his life, past and way of making choices. The weakness is the primordial obstacle the character has to face in order to complete the story. A general rule of thumb is to make the weaknesses more interesting than the character’s strengths.',
    par2: 'Where are they going? This is a tricky question; it has everything to do with the first one. Stablishing the character’s need and desire first gives you an idea of where the character is headed, so now it’s time to think about the endgame for this journey. It’s not only to know where the story physically ends or whether or not the character is gonna achieve the goal. Ask yourself, how hard are they going to try to get what they want, how resilient are they against the obstacles in their paths. What can your characters do to surprise you? This is about creativity, is a question about finding ways to make your characters more resourceful in their ways of acting.',
    par3: 'There you have it, five really interesting questions to make you think about your character, to make you connect with them in a more personal way, but also to start thinking of them as more than people, but as narrative devices and as part of a story, of a design. Okay, that’s it for today, next time we’ll dive into rising action to figure out why it’s so important for the story and as a valuable concept on writing!',
    quote: 'When a character surprises you, encourage them by following them instead of trying to lead them.'
  },
  {
    id: 'E5',
    pos: 5,
    title: 'USE RISING ACTION TO BUILD A BETTER PLOT',
    date: 'OCTOBER 17, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2020/09/And-God-Created-Woman-003.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'What’s this rising action anyway? We’ve been talking about it sometime before, we said it had to do with the conflict the character is facing, right? So let’s dive deeper into this narrative idea to see if it can help us in anyway when facing a new story, okay? In simple terms, rising action is a series of obstacles the character faces when pursuing a goal. It mostly comes down to the antagonist trying to stop the protagonist from achieving the objective, but we can also divide these obstacles into two main categories. External, consider it as any obstacle coming from outside sources, that means outside the protagonist. Internal, consider it as any obstacle coming from inside the character, from his own life and way of being.',
    par2: 'Now, as a general scheme, we can consider rising action as follows; First, the main character wants something. Then some obstacle, may be a thing, a character or their own flaws get in the way of said character, gets in the way of the one thing the character wants. So, the protagonist overcomes a rising set of obstacles, encountering larger and larger ones while moving towards the objective. ',
    par3: 'Not too complicated, right? Desire, obstacle, conflict… these are the elements that you will find in rising action and they’re important to have into consideration when thinking about a story, a sequence or even a scene. This is because, having the idea in mind that every movement driven by desire will meet obstacles in their way to a climax, a chance to fulfil the desire, will certainly make your writing and conflict build better. So, just go with it!',
    quote: 'This happens every time until the protagonist reaches a place where there’s a chance to get what’s desired.'
  },
  {
    id: 'F6',
    pos: 6,
    title: 'THE IMPORTANCE OF STRUCTURE',
    date: 'OCTOBER 24, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2022/04/You-Only-Live-Twice-003.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'So, we’ve been talking about this for a while now. But let’s be honest here, many people just grab a piece of paper and start writing about anything, and chances of landing in a good story this way are not that far off. Many professional writers don’t follow a proper structure, or so they say, and accomplish stories anyway. So, is it really that important to think about one before writing a good ol’ tale? First of all, I think we have to understand something, whether we like it or not, every story follows certain structure, even those we write without thinking in organizing the information will find a way into a stablished form or shape, and there are many shapes to follow! The one we were discussing before, the one most commonly referred as a plot, in its most basic form, it’s composed of; The inciting incident, a character, an obstacle (rising action), a quest. A primitive form of premise to organize all of these elements would be something like this: When an inciting incident happens to a character; they have to overcome rising action to complete the quest.',
    par2: 'But there are other structures that a writer can rely on when devising a new story. And of those other structures, the most basic one, and maybe the one that doesn’t help anyone to write, is the Aristotelian three acts structure. The beginning, set up for characters, their relationship, wants and desires. The middle, rising action until the climax. The end, the plot is resolved. Now, after Aristotle there were obviously other dudes wanting to impose their structures and wisdom upon mankind, one of these bastards is called Horace. He came up with a five acts structure, not to compete with Aristotle or anything, right? It’s called the ABDCE structure. A for Action, must be specific and concrete (active). Involves a character doing something. B for Background, or context before the story started, only essential information here. D for Development, basically the character facing the rising action, forcing them to develop succeeding or failing to overcome obstacles. C for Climax, the higher point in the rising action, the key narrative twist that changes your characters in a real and significant way. E for Ending, this is where the change in the characters is shown, the end of their journey.',
    par3: 'The circle represents the leaving into the unknown and the return back with the fire, with the knowledge from the journey. But in the case of another type of story, like the virgin’s promise, the structure can become something along the lines of a spiral. This structure signals the journey into the inner world, deeper and deeper inside oneself in the hopes to find roots, to find the same fire from the journey into the unknown, just not out there but inside. But these are just some examples of structures a writer can use in their quest into the perilous of developing a new idea. Okay, so that’s it with structures. Next time we’ll make a quick resume of this whole plot idea before moving into other storytelling related stuff, the idea here is to finish this strong base from which we’ll be able to build amazing and complex stories in no time! Actually, a lot of time and effort… Don’t delude yourselves!',
    quote: 'Now, having into consideration structures and all of this, there’s one thing that really makes a difference when thinking about them. This is the circular feeling that some stories have that connects the beginning and the end, the signal of the hero’s journey'
  },
  {
    id: 'G7',
    pos: 7,
    title: 'HERE’S A COOL APPROACH TO PLOT',
    date: 'OCTOBER 31, 2022',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/photo-gallery/Elvis_08.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'We’ve been talking about it for a while now, the PLOT thing. And I also want to say that I’ve read a few screenplays this week and most of them have good dialogues, descent or great descriptions and overall entertaining action, but most of them fail at the plot department. Simply put, the answer to “what’s the story about?” and time and time again I’ve been reading confusing answers to this question. There is a general sense of the concatenation between the scenes, that one and the other are linked by some sort of sense, some forward momentum, yet most of them set something and finish it without taking the time to explore the subject at hand, while others don’t start it at all. ',
    par2: 'So! Here’s a cool way to think about plot in a meaningful yet simple way. A story starts with an initial action, usually a highly dramatic one. The background is the context that offers vivid and crucial information to determine our main character’s actions in the story. In the development phase usually the background causes problems in present time because of the initial action, which brings background to the present via conflict. Also, in the development you outline what your character wants and what’s standing in their way. In the climax there’s a key twist for the story, where all the threads come together. The climax usually ends in a decision to be made. The ending is what happens to your character after the climax.',
    par3: 'There you have it! And I also feel that we’re all understanding a key element in plot, the elements combining together, merging into the character’s path. And this is I feel the most important thing to keep in mind about the whole concept of structure, the thread that connects all the elements is the protagonist, the character and their emotional journey into the unknown, into change.',
    quote: 'This is why it’s so important to have an idea of a plot, in a sense we’re talking about the whole universe of the story moving through the character, shaping them into a new sense of being whether they triumph or fail.'
  },
  {
    id: 'H8',
    pos: 8,
    title: 'WHAT THE HECK IS A SCENE?',
    date: 'JULY 07, 2023',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/2022/08/Licorice-Pizza-041-1.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'Many people have heard the concept made up by Ernest Hemmingway (one crazy individual I may add) about an iceberg theory (which really isn’t that much of a theory, c’mon!). The idea here is that we can only see a tip of what the character is going through, yet the bulk that is moving him is underwater, and is a big bulk or iceberg stuff or whatever. What’s the point here you might be thinking. Basically, that you, as an author, know much more about what’s going on than what you actually put into action, yet somehow the little and subtle elements that you’re using are evoking the entire depth below.',
    par2: 'Now a little quiz. What do you think makes a good scene? No clue? Let me help a bit, let’s focus on three aspects of it, shall we? Argument, there’s a discussion about something. Seduction, some character is trying to convince other about something. Negotiation, in a middle ground there’s a need to come to terms. Of course, there are many other options, we’re just thinking about those that can help create drama, okay?',
    par3: 'Well, that’s about it for today, next time we’ll talk about an infamous rule in writing, the tireless “show, don’t tell” rule, which many people hate and many more worship, all of them real crazy people. Hasta la proxima!',
    quote: 'During a scene, the details used to present an argument, the images and rhetoric that will convince the spectator about the fiction we’re making takes place.'
  },
  {
    id: 'I9',
    pos: 9,
    title: 'FIVE POINTS TO BUILD A SCENE',
    date: 'JULY 14, 2023',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/photo-gallery/Nope_01.jpg?w=1300&ssl=1',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'The scene is the place where characters collide and show themselves, is the opportunity to be, to exist, and the better part is that, in a sequence of scenes, a character grows every time they get the chance to do so. Isn’t that amazing! Okay, so I said I was gonna talk about those 5 points or whatever… they can help you when following the “Show, don’t tell” rule. Let’s review them now:',
    par2: 'Add an action; this may sound obvious, but some people just don’t do it! is not enough to have people talking, you know? you need to have them do something. I mean what the hell do they want?? Keep in mind that something needs to happen and must be something concrete! Dialogue; This is not always needed, let’s be honest here. Understanding that dialogue is the convey of information, please use it to rely information that has something to do with the actual story? please? is it too much to ask? deepen our understanding of the characters or about the plot, use it effectively!! Specific intimate details; Okay I’ll admit it, this sounds kinda pervert, it just does, okay? the idea being that in a scene, in any place where the characters are, we can always learn more about them. Some think about this in the terms of leads or clues or hints at the plot or characters, get it? Inner point of view; this one land more on the novel type of stories, but it can also be used in screenwriting or any other dramatic form. Is the idea of the author, the particular lenses through which we are entering the story.',
    par3: 'Okay, that’s it for today. I feel we really went deep this time, don’t you? and about this show don’t tell rule, just don’t be lazy, okay? use the craft to really imagine the stuff that’s going on. I mean, c’mon! just let enough space for the audience to be a part of it and you’ll be fine. As the most important person in my life often says, it’s all about the balance, and you know what? she’s always right about these things, so listen up!',
    quote: 'Facing the page, what you’re actually doing is building a sequence of scenes. And these scenes are what people will read in the end, is in these dramatic constructions that characters live, do and learn.'
  },
  {
    id: 'J10',
    pos: 10,
    title: 'STEPS FOR EDITING AND REVISION',
    date: 'JULY 21, 2023',
    img: 'https://film-grab.com/wp-content/uploads/2023/04/The-Rain-People-22-1536x830.jpg',
    fade: 0.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'Start with easy fixes; Don’t concentrate immediately in those super complex things like character arc or some blatant plot holes here and there. Just go about checking the typos you’ve had, maybe cut some of those hateful adverbs, run some spell checks. This will familiarize you with the story, because either way you have to read it again to do these easy fixes. Omit needless words; Check the words you’re using, is every single one of them really necessary? Maybe some descriptions you were using went way too poetical or something? Nothing wrong with it, just that many people think this is completely unnecessary given the cold heartless nature of movie producers, right? Insure consistent character motivation; Try to stay consistent about the actions your character is doing in any given scene. If they’re doing something out of character it must be because they’re changing or have changed, not because you suddenly forgot what they were supposed to be like.',
    par2: 'Ask yourself, do I start each scene with something active? A scene must start with an action, right in the stuff, you know. Now, this is not obligatory obviously, many times we start by setting the atmosphere or even the relationship of the characters, but one thing we must never forget is that in any scene the idea is that one character does something because they want something. Finally, Is what you meant in your head clear in the page? Just ask yourself, was my initial idea, those feelings and gut stuff that sets you up for hours and days of typing words into blank spaces, and the actual writing the same? Even similar enough not to end up understanding you wrote a completely different thing? Nothing wrong with that btw, but the idea is that you check if your mental north and the actual writing are pointing in the same direction.',
    par3: 'So, there you have it. Use these steps to really put your script in the next level with some editing and a lot of letting go. Kinda like a working routine for your first draft, which btw, get used to the idea is gonna suck anyways. Just take the pressure off and go at it again, and again and again. That’s the writing gig, as you remember!',
    quote: 'Ask yourself, is my story coherent? Pay attention to the physical and emotional details you’re using in building your world and actions, are they constant throughout the whole script, does any change happen because of the result of actions?'
  },
  {
    id: 'K11',
    pos: 11,
    title: 'CHARACTERS WITH STRONGER MOTIVATION',
    date: 'JULY 28, 2023',
    img: 'https://film-grab.com/wp-content/uploads/2023/04/White-Noise-08.jpg',
    fade: 1.2,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'What does your character want? Have you ever wondered why is this question so repetitive and so important? As it turns out, people and characters always want something, whether it’s some basic need like food or shelter up to the craziest of human endeavors Thing is, to understand the want of a character is to understand their motivation.',
    par2: 'Let’s say you’re a detective, just for the sake of understanding, okay? So, maybe you want to catch the criminal, that’s your want, your motivation for moving your fat ass (filled with donuts and cheap coffee) into action. But maybe, as you go deep into the investigation, you come to realize that the killer is your little kid, turns out the sucker is an acolyte of the devil, a demon, for the non-initiated. So, what do we have here? Conflicting wishes. The motivation line is to catch the criminal. But the desire line is to protect your family. Isn’t that wonderful? Now you have a compelling story about a self-righteous detective who wants to uphold the law, yet can’t go against their baby, finding that their true desire is to protect their family. What will they do?',
    par3: 'I guess it would also depend on another aspect of the character development, their NEED. So, what is this need thing? Well, in simple lame terms it is overcoming a flaw inherent in their personality. Okay, so the idea here is for us to choose a powerful inciting incident that forces the character out of their flawed life and into the story. Now, why would they NEED to go through such an ordeal? Because it seems that this is the only way to resolve their flaw, by addressing it in an external situation which is comprised of the world of the story and the antagonism.',
    quote: 'As it turns out, people and characters always want something, whether it’s some basic need like food or shelter up to the craziest of human endeavors.'
  },
  {
    id: 'L12',
    pos: 12,
    title: 'THEME IS IMPORTANT IN YOUR SCRIPT',
    date: 'AUGUST 05, 2023',
    img: 'https://i0.wp.com/film-grab.com/wp-content/uploads/photo-gallery/02%20(186).jpg?w=1300&ssl=1',
    fade: 0.8,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'As an invisible force guiding every movement of creation, Theme might stand as the most important aspect of any artistic creation. Think of theme as the symbolic argument between a posited truth and a lie, two opposing aspects of some idea that will play out in the characters’ arcs and throughout an external plot, which in turn will force characters’ growth. Generally speaking, theme is a uniform idea or subject, explored via recurring patterns and expanded through comparisons and contrast.',
    par2: 'So, how can you find the theme of a story? Look for the truth at the heart of any prominent character change within the plot. Then, identify any underlying topics or recurring motifs repeated throughout your plot and characters’ decisions. But take special notice of the ending of your story, because this is where ultimately the theme is expressed or revealed as a truth discovered or accepted by the protagonist (often called a self-revelation). This truth is often called the thematic point, once discovered, you can play it back against everything that happened previously in the plot and characters’ development. Ideally, you will see it resonate in every scene, if not you should strive for it to happen.',
    par3: 'Now, let’s talk a bit about the differences between using and finding a theme for your story. If we start a story from a theme, we can actually mold the plot and characters into a visual and external metaphor for an invisible theme. But if we don’t, let’s say we started with character or plot, the idea is not to construct a metaphor, but rather discover one inside our story. In this case, we should look within the existing/evolving plot to identify the emerging theme.',
    quote: 'Generally speaking, theme is a uniform idea or subject, explored via recurring patterns and expanded through comparisons and contrast.'
  },
  {
    id: 'M13',
    pos: 13,
    title: 'USE THEME FOR CHARACTERS AND CONFLICT',
    date: 'AUGUST 12, 2023',
    img: 'https://film-grab.com/wp-content/uploads/2023/03/Green-Knight-32-1536x830.jpg',
    fade: 0.4,
    tag: 'SCREENWRITING TECHNIQUE',
    par1: 'As we discussed before, a theme is an argument between two posited ideas, a TRUTH, and a LIE. And so, a thematic premise has two opposite sides; A truth that must be discovered and a lie that is believed. Discovered and believed by whom you might ask. Well, obviously we’re talking about the story’s protagonist, right? Do you remember when we talked about needs and wants? Think about it like this; Truth = Need and Lie= Want.',
    par2: 'Most of the time, a protagonist enters the plot because they believe some lie that is expressed as a desire or want. Yet in reality, what they really need is to get a sense of a deeper truth they can’t initially see. This truth has the power to make them change in profound ways. A character’s conflict with others or with the world of the story is almost inevitably a reflection and/or a projection of inner conflicts. In other words, the plot reflects/projects the character’s inner struggle upon an external world. Also, lies and truths will often translate into literal objects, persons, or states within the external plot. At the root of it, there’s a ghost from the character’s past. Remember what ghost is? Simply put… TRAUMA!',
    par3: 'The ghost or trauma makes the character believe a lie that throws them into the plot because of their desires, then facing rising action that expresses many variations on the theme being conveyed and ending in the plot goal or objective, where the truth the character needs to grow is expressed. So, the protagonist’s final choice in the story is between what they want and what they need and it will mostly be externalized in a metaphor that proves a corresponding choice between the lie and the truth.',
    quote: 'And so, a thematic premise has two opposite sides; A truth that must be discovered and a lie that is believed.'
  }
]